### ISSUE TITLE
Add usage example

### ISSUE THREAD

**Issue by TrejGun** [nest-bots/platform-bot#69]
It would be awesome to see code examples and working example

**Comment by xcf-t** [comment]
I will work on updating the project in the next few days

**Comment by TrejGun** [comment]
Hey man! I'm back to this again :) Is there anything you can share,  please?

**Comment by xcf-t** [comment]
I have started working on this project again about a week ago... I am currently only writing the discord bot part, I will update you once I got everything to work

**Comment by TrejGun** [comment]
oh nice! i'm interested in telegram integration right now and will appreciate any help

**Comment by xcf-t** [comment]
I found it more difficult to combine the different bot platforms, but I can definitely help you with the implementation of a telegram integration for nestjs
